const fs = require('fs'), vm = require('vm'), assert = require('assert/strict');
const root = require('path').resolve(__dirname, '..');
const results = [];
function env() {
 const elements = new Map();
 const html = fs.readFileSync(root+'/popup.html','utf8');
 for(const match of html.matchAll(/\bid="([^"]+)"/g)) elements.set(match[1],{id:match[1],value:'',textContent:'',innerHTML:'',style:{},hidden:false,classList:{add(){},remove(){},toggle(){}},listeners:{},addEventListener(type,fn){(this.listeners[type]??=[]).push(fn)},querySelector(){return null},querySelectorAll(){return[]},getAttribute(){return null},setAttribute(){},append(){},replaceChildren(){},focus(){}});
 const document = {body:{appendChild(){}},getElementById:id=>elements.get(id)||null,querySelector:()=>null,querySelectorAll:()=>[],createElement:()=>({style:{},append(){},appendChild(){},setAttribute(){},addEventListener(){}}),addEventListener(){}};
 let currentChat = 'chatA'; let calls=[]; let payloads=[]; let timeOffset=0; let handler=async()=> 'OK';
 const ClockDate=class extends Date {static now(){return Date.now()+timeOffset}};
 const listeners={};
 const ctx={extensionSettings:{},name1:'Bob',name2:'Alice',characterId:0,characters:[{name:'Alice',avatar:'alice.png',chat:'chatA'}],chat:[],maxContext:100000,chatId:'chatA',getCurrentChatId:()=>currentChat,saveSettingsDebounced(){},setExtensionPrompt(){},getCharacterCardFields:()=>({description:'SOURCE Appearance: red hair. Has wings. Former doctor.',personality:'Careful, dry humor; avoids waste.',persona:'User is an optimistic courier.',mesExamples:'Alice: Do not waste the last bandage.',firstMessage:'Checks the supply cabinet.'}),eventSource:{on(type,fn){(listeners[type]??=[]).push(fn)},removeListener(type,fn){listeners[type]=(listeners[type]||[]).filter(x=>x!==fn)},async emit(type,...args){for(const fn of listeners[type]||[])await fn(...args)}},event_types:{CHAT_COMPLETION_SETTINGS_READY:'settings',GENERATION_STOPPED:'stop',GENERATION_STARTED:'start',GENERATION_ENDED:'end',CHAT_CHANGED:'changed',CHARACTER_MESSAGE_RENDERED:'rendered'}};
 const sandbox={window:{AUWB:{},addEventListener(){}},document,SillyTavern:{getContext:()=>ctx},console,AbortController,Map,Set,Array,Date:ClockDate,Math,JSON,setTimeout,clearTimeout,setInterval,clearInterval,requestAnimationFrame:()=>{},fetch:async(url,options)=>{const body=JSON.parse(options.body);payloads.push(body);const prompt=body.messages[0].content;calls.push(prompt);const answer=await handler(prompt);return{ok:true,json:async()=>({choices:[{message:{content:typeof answer==='string'?answer:answer.text},finish_reason:typeof answer==='string'?'stop':answer.finish}]})}}};
 vm.createContext(sandbox); for(const file of ['core','sections','engine','ui','quality'])vm.runInContext(fs.readFileSync(root+'/lib/'+file+'.js','utf8'),sandbox,{filename:file+'.js'});
 const A=sandbox.window.AUWB; const settings=A.getSettings(); settings.apiSource='openai'; settings.customApiUrl='https://test.invalid'; settings.genOptions.speedMode='thorough';settings.genOptions.planningEnabled=false;settings.genOptions.qualityAudit=false;
 A.showStatus=()=>{}; A.updateExtensionPrompt=()=>{}; A.updateTokenDisplay=()=>{}; A.renderHistoryList=()=>{};
 return {A,ctx,settings,elements,document,calls,payloads,window:sandbox.window,setFetch:fn=>sandbox.fetch=fn,advanceTime:ms=>timeOffset+=ms,setHandler:fn=>handler=fn,switchChat:id=>{currentChat=id;ctx.chatId=id;ctx.characters[0].chat=id;A.onQualityChatChanged();A.invalidateCharInfoCache();A.invalidateSectionCache();}};
}
const facts={char:{personality:['careful decisions','dry humor'],age:[],appearance:['red hair'],abilities:['wings'],background:['former doctor'],relationships:[]},user:{personality:['optimistic'],age:[],appearance:[],abilities:[],background:['courier'],relationships:[]}};
async function test(name,fn){try{await fn();results.push({name,passed:true});console.log('PASS '+name)}catch(e){results.push({name,passed:false,error:e.stack});console.error('FAIL '+name+'\n'+e.stack)}}
(async()=>{
await test('All built-in sections and custom-only responses parse without becoming world',async()=>{let e=env();for(const s of e.A.BUILTIN_SECTIONS){const parsed=e.A.parseGeneratedContent(`[${s.tag}]내용[/${s.tag}]`);assert.equal(parsed[s.id],'내용');assert.equal(Object.keys(parsed).length,1)}e.A.getSettings().customSections.push({id:'custom_demo',label:'추가'});e.A.invalidateSectionCache();assert.equal(e.A.parseGeneratedContent('[CUSTOM_demo]추가내용[/CUSTOM_demo]').custom_demo,'추가내용')});
await test('Mixed tagged/heading output merges and malformed prose is not a world',async()=>{let e=env();const parsed=e.A.parseGeneratedContent('[WORLD]세계[/WORLD]\n## CHAR_PERSONALITY\n성격');assert.equal(parsed.world,'세계');assert.equal(parsed.charPersonality,'성격');assert.equal(Object.keys(e.A.parseGeneratedContent('Sorry, cannot generate.')).length,0);assert.equal(Object.keys(e.A.parseGeneratedContent('[WORLD]unfinished')).length,0)});
await test('Duplicate tags are rejected; JSON sections parse',async()=>{let e=env();assert.throws(()=>e.A.parseGeneratedContent('[WORLD]a[/WORLD][WORLD]b[/WORLD]'),/중복/);assert.equal(e.A.parseGeneratedContent('{"sections":{"userClothing":"coat"}}').userClothing,'coat')});
await test('Missing and unresolved template content are detected',async()=>{let e=env();assert.equal(e.A.validateSections({world:'{{GUIDELINES}}'},['world']).valid,false);assert.equal(e.A.validateSections({},['charSetting']).missing[0],'charSetting')});
await test('Nested section commits and genre commits work inside guarded operation',async()=>{let e=env();await e.A.runOperation(async()=>{e.A.setSectionContent('charPersonality','new traits');e.A.setSectionTextareaValue('charPersonality','new traits');e.A.saveChatData('genrePrompt','light');e.A.setVal('auwb-genre-prompt','light');e.A.assertOperation()});assert.equal(e.A.getSectionContent('charPersonality'),'new traits')});
await test('Chat-bound pending save survives chat switch without contamination',async()=>{let e=env();const old=e.A.getCurrentChatId();e.A.scheduleChatSave('world','old chat edit');e.switchChat('chatB');assert.equal(e.settings.chatData[old].worldSetting,'old chat edit');assert.equal(e.A.getSectionContent('world'),'')});
await test('In-flight response is rejected after chat switch',async()=>{let e=env();let release;let started;const wait=new Promise(r=>started=r);e.setHandler(()=>new Promise(r=>{release=r;started()}));const task=e.A.runOperation(()=>e.A.callAPI('test'));await wait;e.switchChat('chatB');release('result');await assert.rejects(task,/취소|변경/);assert.equal(e.A.getSectionContent('world'),'')});
await test('Editing during generation protects new text',async()=>{let e=env();await e.A.runOperation(async()=>{e.elements.get('auwb-world-setting-content').value='manual new edit';assert.throws(()=>e.A.assertOperation(),/편집/)});assert.equal(e.elements.get('auwb-world-setting-content').value,'manual new edit')});
await test('API calls are serialized',async()=>{let e=env();let active=0,max=0;e.setHandler(async()=>{active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,5));active--;return'OK'});await Promise.all([e.A.callAPI('a'),e.A.callAPI('b')]);assert.equal(max,1)});
await test('Source extraction filters both people and supplies dialogue evidence',async()=>{let e=env();e.settings.genOptions.sourceDetailEnabled=true;e.settings.genOptions.sourceDetailAspects={personality:true};e.setHandler(async()=>JSON.stringify(facts));await e.A.runOperation(async()=>{const source=await e.A.prepareSource();assert.equal(source.char.appearance.length,0);assert.equal(source.char.abilities.length,0);assert.equal(source.user.background.length,0);assert.equal(source.char.personality.length,2);const pi=e.A.getCharInfoForPrompt();assert.ok(!pi.charDesc.includes('red hair'));assert.ok(!pi.charDesc.includes('former doctor'))});assert.ok(e.calls[0].includes('Do not waste the last bandage'))});
await test('Full reinvention does not send source to extraction',async()=>{let e=env();e.settings.genOptions.original='break';await e.A.runOperation(async()=>{await e.A.prepareSource();assert.equal(e.A.getCharInfoForPrompt().charDesc.includes('red hair'),false)});assert.equal(e.calls.length,0)});
await test('Missing requested section is repaired and unselected context retained',async()=>{let e=env();e.A.setSectionContent('world','preserved world');e.A.setSectionTextareaValue('world','preserved world');e.setHandler(async p=>p.includes('Extract established facts')?JSON.stringify(facts):p.includes('## REPAIR')?'[USER_PERSONALITY]user traits[/USER_PERSONALITY]':'[CHAR_PERSONALITY]char traits[/CHAR_PERSONALITY]');let result=await e.A.runOperation(()=>e.A.generateAUWorld('courier AU',['charPersonality','userPersonality']));let parsed=e.A.parseGeneratedContent(result);assert.equal(parsed.userPersonality,'user traits');assert.equal(parsed.charPersonality,'char traits');assert.ok(e.calls.some(p=>p.includes('preserved world')));assert.equal(e.A.getSectionContent('charPersonality'),'')});
await test('Unrepairable result throws without overwriting existing content',async()=>{let e=env();e.A.setSectionContent('world','original');e.A.setSectionTextareaValue('world','original');e.setHandler(async p=>p.includes('Extract established facts')?JSON.stringify(facts):'invalid prose');await assert.rejects(e.A.runOperation(()=>e.A.generateAUWorld('AU',['world'])),/완전한|완성하지/);assert.equal(e.A.getSectionContent('world'),'original')});
await test('Truncated API response preserves complete sections and repairs missing ones',async()=>{let e=env();e.setHandler(async p=>p.includes('Extract established facts')?JSON.stringify(facts):p.includes('## REPAIR')?'[USER]user[/USER]':{text:'[CHAR]char[/CHAR]\n[USER]cut',finish:'length'});let result=await e.A.runOperation(()=>e.A.generateAUWorld('AU',['charSetting','userSetting']));let parsed=e.A.parseGeneratedContent(result);assert.equal(parsed.charSetting,'char');assert.equal(parsed.userSetting,'user')});
await test('Locked section excluded from all generation and refine paths',async()=>{let e=env();e.settings.sectionConfig.charSetting.locked=true;await assert.rejects(e.A.runOperation(()=>e.A.generateAUWorld('AU',['charSetting'])),/잠금/);await assert.rejects(e.A.runOperation(()=>e.A.refineSection('charSetting','specific')),/잠금/);assert.equal(e.calls.length,0)});
await test('Batch regeneration uses filtered source and the shared directives',async()=>{let e=env();e.settings.genOptions.mustExclude='NO_CONSPIRACY';e.settings.genOptions.sourceDetailEnabled=true;e.settings.genOptions.sourceDetailAspects={personality:true};e.setHandler(async p=>p.includes('Extract established facts')?JSON.stringify(facts):'[CHAR_PERSONALITY]new traits[/CHAR_PERSONALITY]');await e.A.runOperation(()=>e.A.batchRegenerateSections(['charPersonality']));const prompt=e.calls[e.calls.length-1];assert.ok(prompt.includes('NO_CONSPIRACY'));assert.ok(!prompt.includes('red hair'));assert.ok(prompt.includes('PLAYER AGENCY'));assert.ok(!prompt.includes('{{GUIDELINES}}'))});
await test('Two-pass uses bullet outlines and validates both phases',async()=>{let e=env();e.settings.genOptions.twoPassEnabled=true;e.setHandler(async p=>p.includes('Extract established facts')?JSON.stringify(facts):p.includes('SKELETON OUTLINE')?'[WORLD]- bullet one\n- bullet two[/WORLD]':'[WORLD]expanded[/WORLD]');await e.A.runOperation(()=>e.A.generateAUWorld('AU',['world']));const skeleton=e.calls.find(p=>p.includes('SKELETON OUTLINE'));assert.ok(skeleton.includes('2–3 concise factual bullet'));assert.ok(!skeleton.includes('3P:'));assert.ok(e.calls[e.calls.length-1].includes('VALIDATED OUTLINE'))});
await test('Exact selection offsets rewrite second duplicate only',async()=>{let e=env();e.A.setSectionContent('world','same / same');e.A.setSectionTextareaValue('world','same / same');e.setHandler(async p=>p.includes('Extract established facts')?JSON.stringify(facts):'changed');const result=await e.A.runOperation(()=>e.A.regenerateSectionPartial('world','same','change',{start:7,end:11}));assert.equal(result.value,'same / changed');assert.ok(e.calls[e.calls.length-1].includes('Other settings'))});
await test('Self-critique passes actual problem/fix to repair and verifies the repair',async()=>{let e=env();e.A.setSectionContent('world','old');e.A.setSectionTextareaValue('world','old');e.setHandler(async p=>p.includes('Extract established facts')?JSON.stringify(facts):p.startsWith('Audit AU')?JSON.stringify({issues:[{section:'world',problem:'NO_CAUSAL_MECHANISM',fix:'ADD_WORKING_MECHANISM',severity:'major'}]}):p.startsWith('Verify whether')?'{"unresolved":[]}':'[WORLD]new causal mechanism[/WORLD]');const res=await e.A.runOperation(()=>e.A.runSelfCritique());assert.equal(res.improved,1);assert.ok(e.calls.some(p=>p.includes('ADD_WORKING_MECHANISM')&&p.startsWith('Apply ONLY')));assert.equal(e.A.getSectionContent('world'),'new causal mechanism')});
await test('Auto-update uses full unprocessed range and advances cursor only after success',async()=>{let e=env();e.settings.smartAutoUpdate=false;e.A.saveChatData('lastProcessedMessage',1);e.ctx.chat=Array.from({length:8},(_,i)=>({mes:'message '+i,is_user:i%2===0}));let got;e.A.updateFromRange=async(s,t)=>{got=[s,t];return'[NO_CHANGES]'};await e.A.triggerAutoUpdate();assert.deepEqual(got,[2,7]);assert.equal(e.A.getChatData().lastProcessedMessage,7);e.ctx.chat.push({mes:'next'});e.A.updateFromRange=async()=>{throw Error('failed')};await e.A.triggerAutoUpdate();assert.equal(e.A.getChatData().lastProcessedMessage,7)});
await test('Chat identity includes character/group and legacy data migrates',async()=>{let e=env();assert.ok(e.A.getCurrentChatId().startsWith('character:alice.png/'));e.settings.chatData.chatA={worldSetting:'legacy'};assert.equal(e.A.getChatData().worldSetting,'legacy');e.ctx.groupId='g1';assert.ok(e.A.getCurrentChatId().startsWith('group:g1/'))});
await test('Popup ids are unique and all quality controls exist',async()=>{const html=fs.readFileSync(root+'/popup.html','utf8');const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length);for(const id of ['auwb-plan-modal','auwb-plan-options','auwb-plan-cancel','auwb-cancel-operation','auwb-request-record','auwb-quality-audit','auwb-user-freedom'])assert.ok(ids.includes(id))});
await test('Quality UI initializes and syncs new controls',async()=>{let e=env();e.A.initQualityUI();assert.equal(e.elements.get('auwb-user-freedom').value,'persona');assert.equal(e.elements.get('auwb-plan-selection').value,'auto');assert.equal(e.elements.get('auwb-injection-mode').value,'full');assert.equal(typeof e.elements.get('auwb-cancel-operation').onclick,'function')});
await test('Complete UI event binding initializes without runtime errors',async()=>{let e=env();e.A.bindUIEvents();e.A.initQualityUI();assert.ok(e.elements.get('auwb-generate-btn').listeners.click.length)});
await test('Automatic updates wait for normal chat generation to end',async()=>{let e=env();e.settings.autoUpdateEnabled=true;e.settings.autoUpdateInterval=1;let count=0;e.A.triggerAutoUpdate=async()=>{if(!e.A.chatGenerationActive)count++};assert.equal(e.A.registerPromptInjection(),true);await e.ctx.eventSource.emit('start');await e.ctx.eventSource.emit('rendered',1,'normal');assert.equal(count,0);await e.ctx.eventSource.emit('end');assert.equal(count,1);await e.ctx.eventSource.emit('rendered',1,'normal');assert.equal(e.A.autoUpdateMessageCount,1)});
await test('Summary injection uses matching source and falls back on changed content',async()=>{let e=env();e.A.setSectionContent('world','long original');e.A.saveChatData('injectionMode','compact');e.A.saveChatData('injectionSummary',{sources:{world:'long original'},sections:{world:'short'}});assert.equal(e.A.getInjectionContent('world'),'short');e.A.setSectionContent('world','new original');assert.equal(e.A.getInjectionContent('world'),'new original')});
await test('Summary creation verifies essential fact preservation before saving',async()=>{let e=env();e.A.setSectionContent('world','long setting');e.A.setSectionTextareaValue('world','long setting');e.setHandler(async p=>p.startsWith('Compare compact')?'{"issues":[]}':'{"sections":{"world":"compact"}}');await e.A.runOperation(()=>e.A.buildInjectionSummaries());assert.equal(e.A.getInjectionContent('world'),'compact');assert.equal(e.A.getChatData().injectionMode,'compact')});
await test('Sequential pipeline handles custom-only stage and carries prior phase context',async()=>{let e=env();e.settings.genOptions.sequentialEnabled=true;e.settings.customSections.push({id:'custom_demo',label:'custom'});e.A.invalidateSectionCache();e.setHandler(async p=>p.includes('Extract established facts')?JSON.stringify(facts):p.includes('CUSTOM_demo')?'[CUSTOM_demo]custom[/CUSTOM_demo]':p.includes('CHAR_PERSONALITY')?'[CHAR_PERSONALITY]character[/CHAR_PERSONALITY]':'[WORLD]world[/WORLD]');let result=await e.A.runOperation(()=>e.A.generateAUWorld('AU',['world','charPersonality','custom_demo']));assert.equal(e.A.parseGeneratedContent(result).custom_demo,'custom');assert.ok(e.calls[e.calls.length-1].includes('[WORLD]\nworld'))});
await test('Player role-only mode removes extracted user personality',async()=>{let e=env();e.settings.genOptions.userFreedom='role';e.setHandler(async()=>JSON.stringify(facts));await e.A.runOperation(async()=>{const source=await e.A.prepareSource();assert.equal(source.user.personality.length,0);assert.ok(e.A.buildGuidelines().includes('Do not invent user emotions'))})});
await test('Very small output budget caps single-section targets',async()=>{let e=env();e.settings.customApiMaxTokens=256;e.settings.genOptions.outputVolume='very_long';e.settings.genOptions.detailDepth='extreme';const text=e.A.buildOutputFormat(['world']);assert.ok(text.includes('153 output tokens'))});
await test('SillyTavern requests set response length and preserve profile serialization',async()=>{let e=env();e.settings.apiSource='sillytavern';let got;e.ctx.generateRaw=async args=>{got=args;return'raw result'};assert.equal(await e.A.callAPI('prompt'),'raw result');assert.equal(got.responseLength,4000);assert.equal(got.trimNames,false)});
await test('Generate button runs guarded pipeline and commits validated result',async()=>{let e=env();e.A.renderCustomSectionContent=()=>{};e.A.bindUIEvents();e.A.initQualityUI();e.elements.get('auwb-au-concept').value='courier AU';e.document.querySelectorAll=selector=>selector.includes('auwb-gen-section-select')?[{value:'world'}]:[];e.setHandler(async p=>p.includes('Extract established facts')?JSON.stringify(facts):'[WORLD]generated world[/WORLD]');await e.elements.get('auwb-generate-btn').listeners.click[0]();assert.equal(e.A.getSectionContent('world'),'generated world');assert.equal(e.A.getChatData().auConcept,'courier AU');assert.equal(e.elements.get('auwb-generate-btn').disabled,false)});
await test('API cancellation does not retry or apply stale results',async()=>{let e=env();let release,started;const ready=new Promise(r=>started=r);e.setHandler(()=>new Promise(r=>{release=r;started()}));const pending=e.A.runOperation(()=>e.A.callAPIWithRetry('cancel'));await ready;e.A.cancelOperation();release('late');await assert.rejects(pending,/취소/);assert.equal(e.calls.length,1)});
await test('Smart analysis receives all section summaries rather than first 500 chars',async()=>{let e=env();e.A.setSectionContent('world','x'.repeat(800));e.A.setSectionContent('charRelation','RELATION_AT_END');e.setHandler(async()=> 'NO_UPDATE_NEEDED');assert.equal(await e.A.shouldUpdate(0,0),false);assert.ok(e.calls[0].includes('RELATION_AT_END'))});
await test('Brainstorm respects custom creative template and validates three ideas',async()=>{let e=env();e.settings.customPrompts.brainstorm='CUSTOM_CREATIVE_RULE {{CONCEPT}}';e.setHandler(async p=>p.includes('Extract established facts')?JSON.stringify(facts):'{"ideas":[{"title":"a","summary":"a"},{"title":"b","summary":"b"},{"title":"c","summary":"c"}]}');const ideas=await e.A.runOperation(()=>e.A.generateBrainstorm('AU'));assert.equal(ideas.length,3);assert.ok(e.calls[e.calls.length-1].includes('CUSTOM_CREATIVE_RULE AU'))});
await test('Planning selects the recommended coherent design and passes it to generation',async()=>{let e=env();e.settings.genOptions.planningEnabled=true;const candidate={title:'Night courier',mechanism:'Night-only deliveries',consequences:['shift work','shared depot'],charTranslation:'carefulness becomes inventory checks',userRole:'courier with open choices',interaction:'shared deliveries',opening:'late parcel',rules:'limited hours',distinctness:'incentive-based contact'};e.setHandler(async p=>p.includes('Extract established facts')?JSON.stringify(facts):p.startsWith('Design exactly')?JSON.stringify({recommendedIndex:1,candidates:[candidate,candidate,candidate]}):'[WORLD]world[/WORLD]');await e.A.runOperation(()=>e.A.generateAUWorld('AU',['world']));assert.equal(e.A.lastPlan.title,'Night courier');assert.ok(e.calls[e.calls.length-1].includes('APPROVED DESIGN'));assert.ok(e.calls[e.calls.length-1].includes('Night-only deliveries'))});
await test('No active chat blocks generation without issuing API calls',async()=>{let e=env();e.switchChat(null);await assert.rejects(e.A.runOperation(()=>e.A.generateAUWorld('AU',['world'])),/채팅/);assert.equal(e.calls.length,0)});
await test('What-If preserves locked world and uses common generation constraints',async()=>{let e=env();e.A.setSectionContent('world','LOCKED_WORLD');e.A.setSectionTextareaValue('world','LOCKED_WORLD');e.settings.sectionConfig.world.locked=true;for(const s of e.A.BUILTIN_SECTIONS)if(!['world','charSetting'].includes(s.id))e.settings.sectionConfig[s.id].enabled=false;e.A.invalidateSectionCache();e.setHandler(async p=>p.includes('Extract established facts')?JSON.stringify(facts):'[CHAR]changed role[/CHAR]');const result=await e.A.runOperation(()=>e.A.generateWhatIf('The delivery failed'));const parsed=e.A.parseGeneratedContent(result);assert.equal(parsed.charSetting,'changed role');assert.equal(parsed.world,undefined);assert.ok(e.calls[e.calls.length-1].includes('LOCKED_WORLD'));assert.ok(e.calls[e.calls.length-1].includes('PLAYER AGENCY'))});
await test('Ordinary chat generation blocks profile switching requests',async()=>{let e=env();e.settings.apiSource='sillytavern';e.ctx.isGenerating=true;e.ctx.generateRaw=async()=>{throw Error('must not run')};await assert.rejects(e.A.callAPI('test'),/채팅 응답/)});
await test('Removed custom sections clear previously registered injection modules',async()=>{let e=env();const seen=[];e.ctx.setExtensionPrompt=(...args)=>seen.push(args);e.settings.customSections.push({id:'custom_demo',label:'Custom'});e.A.invalidateSectionCache();e.A.setSectionContent('custom_demo','content');e.A.initQualityUI();e.A._doUpdateExtensionPrompt();e.settings.customSections=[];e.A.invalidateSectionCache();e.A._doUpdateExtensionPrompt();assert.ok(seen.some(args=>args[0]==='au_wb_custom_demo'&&args[1]===''&&args[2]===-1))});

await test('CSS disabled overlay decodes to the correct Korean label',async()=>{const css=fs.readFileSync(root+'/style.css','utf8');const block=css.match(/\.auwb-section-disabled::after\s*\{([^}]+)/)[1];const value=block.match(/content:\s*'([^']+)'/)[1].replace(/\\([0-9a-f]{1,6})/gi,(_,hex)=>String.fromCodePoint(parseInt(hex,16)));assert.equal(value,'비활성화');assert.equal(css.includes('�'),false)});
await test('Stale GENERATION_STARTED flag does not reject a real idle host',async()=>{let e=env();e.settings.apiSource='sillytavern';e.A.chatGenerationActive=true;e.ctx.isGenerating=()=>false;e.ctx.generateRaw=async()=> 'generated';assert.equal(await e.A.callAPI('idle'),'generated');assert.equal(e.A.chatGenerationActive,false)});
await test('Hidden stop button with flex display does not imply an active request',async()=>{let e=env();e.settings.apiSource='sillytavern';e.A.chatGenerationActive=true;e.elements.set('mes_stop',{getClientRects:()=>[]});e.window.getComputedStyle=()=>({display:'flex',visibility:'visible'});e.ctx.generateRaw=async()=> 'generated';assert.equal(await e.A.callAPI('idle'),'generated')});
await test('Dry-run and quiet events do not mark chat generation as active',async()=>{let e=env();e.A.registerPromptInjection();await e.ctx.eventSource.emit('start','normal',{},true);assert.notEqual(e.A.chatGenerationActive,true);await e.ctx.eventSource.emit('start','quiet',{},false);assert.notEqual(e.A.chatGenerationActive,true)});
await test('Fast full-AU generation uses exactly one request despite enabled advanced toggles',async()=>{let e=env();e.settings.genOptions.speedMode='fast';e.settings.genOptions.planningEnabled=true;e.settings.genOptions.qualityAudit=true;e.settings.genOptions.twoPassEnabled=true;e.settings.genOptions.sequentialEnabled=true;const response=e.A.BUILTIN_SECTIONS.map(sec=>'['+sec.tag+']complete '+sec.id+'[/'+sec.tag+']').join('\n');e.setHandler(async()=>response);const result=await e.A.runOperation(()=>e.A.generateAUWorld('courier AU'));assert.equal(Object.keys(e.A.parseGeneratedContent(result)).length,11);assert.equal(e.calls.length,1);assert.ok(e.calls[0].includes('Careful, dry humor'));assert.equal(e.payloads[0].reasoning_effort,'low')});
await test('Filtered source extraction is cached across repeated generation operations',async()=>{let e=env();e.settings.genOptions.sourceDetailEnabled=true;e.settings.genOptions.sourceDetailAspects={personality:true};e.setHandler(async()=>JSON.stringify(facts));await e.A.runOperation(()=>e.A.prepareSource());await e.A.runOperation(()=>e.A.prepareSource());assert.equal(e.calls.length,1);e.settings.genOptions.sourceDetailAspects.appearance=true;await e.A.runOperation(()=>e.A.prepareSource());assert.equal(e.calls.length,2)});
await test('Optional audit failure does not discard validated generated output',async()=>{let e=env();e.settings.genOptions.qualityAudit=true;e.setHandler(async p=>p.includes('Extract established facts')?JSON.stringify(facts):p.startsWith('Audit AU')?'not JSON':'[WORLD]validated world[/WORLD]');const result=await e.A.runOperation(()=>e.A.generateAUWorld('AU',['world']));assert.equal(e.A.parseGeneratedContent(result).world,'validated world');assert.equal(e.A.lastAudit.unresolved.length,1)});
await test('Partial output survives failed repair and can be explicitly recovered',async()=>{let e=env();e.settings.genOptions.speedMode='fast';e.A.renderCustomSectionContent=()=>{};e.A.initQualityUI();e.setHandler(async p=>p.includes('## REPAIR')?'invalid':'[CHAR]completed char[/CHAR]');await assert.rejects(e.A.runOperation(()=>e.A.generateAUWorld('AU',['charSetting','userSetting'])),/완성하지/);assert.equal(e.A.getSectionContent('charSetting'),'');assert.equal(e.A.getChatData().generationDraft.sections.charSetting,'completed char');await e.elements.get('auwb-recover-draft').onclick();assert.equal(e.A.getSectionContent('charSetting'),'completed char');assert.equal(e.A.getSectionContent('userSetting'),'')});
await test('Overall operation deadline prevents launching more requests',async()=>{let e=env();e.settings.genOptions.operationTimeout=30;await assert.rejects(e.A.runOperation(async()=>{e.advanceTime(31000);await e.A.callAPI('too late')}),/전체 작업 시간/);assert.equal(e.calls.length,0)});
await test('Reasoning hook only changes the extension-owned request and removes itself',async()=>{let e=env();e.settings.apiSource='sillytavern';e.ctx.isGenerating=()=>false;let related,unrelated;e.ctx.generateRaw=async args=>{unrelated={messages:[{content:'ordinary chat'}],reasoning_effort:'high'};related={messages:[{content:args.prompt}],reasoning_effort:'high'};await e.ctx.eventSource.emit('settings',unrelated);await e.ctx.eventSource.emit('settings',related);return'result'};await e.A.callAPI('owned prompt');assert.equal(related.reasoning_effort,'low');assert.equal(unrelated.reasoning_effort,'high');const after={messages:[{content:'owned prompt'}],reasoning_effort:'high'};await e.ctx.eventSource.emit('settings',after);assert.equal(after.reasoning_effort,'high')});
await test('Input context pressure reduces output reservation instead of rejecting a fitting request',async()=>{let e=env();e.settings.apiSource='sillytavern';e.ctx.isGenerating=()=>false;e.ctx.maxContext=5000;e.ctx.getTokenCountAsync=async()=>2000;let length;e.ctx.generateRaw=async args=>{length=args.responseLength;return'result'};await e.A.callAPI('prompt');assert.equal(length,2872)});
await test('Progress shows active phase and request count and clears after completion',async()=>{let e=env();e.settings.genOptions.speedMode='fast';let release,started;const ready=new Promise(r=>started=r);e.setHandler(()=>new Promise(r=>{release=r;started()}));const pending=e.A.runOperation(()=>e.A.generateAUWorld('AU',['world']));await ready;assert.ok(e.elements.get('auwb-operation-progress').textContent.includes('요청 1회'));release('[WORLD]world[/WORLD]');await pending;assert.equal(e.elements.get('auwb-operation-progress').textContent,'')});


await test('Unsupported reasoning effort is omitted and remembered for Custom API',async()=>{let e=env();let requests=0;const bodies=[];e.setFetch(async(url,options)=>{requests++;const body=JSON.parse(options.body);bodies.push(body);if(body.reasoning_effort)return{ok:false,status:400,text:async()=>'unsupported parameter reasoning_effort'};return{ok:true,json:async()=>({choices:[{message:{content:'OK'},finish_reason:'stop'}]})}});assert.equal(await e.A.callAPI('first'),'OK');assert.equal(await e.A.callAPI('second'),'OK');assert.equal(requests,3);assert.equal(bodies[0].reasoning_effort,'low');assert.equal(bodies[1].reasoning_effort,undefined);assert.equal(bodies[2].reasoning_effort,undefined)});
await test('Current connection reasoning setting is retained when auto is selected',async()=>{let e=env();e.settings.genOptions.reasoningEffort='auto';await e.A.callAPI('test');assert.equal(e.payloads[0].reasoning_effort,undefined)});
await test('Fast strict source filtering extracts once then generates directly',async()=>{let e=env();e.settings.genOptions.speedMode='fast';e.settings.genOptions.sourceDetailEnabled=true;e.settings.genOptions.sourceDetailAspects={personality:true};e.setHandler(async p=>p.includes('Extract established facts')?JSON.stringify(facts):'[WORLD]world[/WORLD]');await e.A.runOperation(()=>e.A.generateAUWorld('AU',['world']));assert.equal(e.calls.length,2);await e.A.runOperation(()=>e.A.generateAUWorld('AU',['world']));assert.equal(e.calls.length,3);assert.ok(!e.calls[2].includes('red hair'))});

if(process.env.AUWB_TEST_REPORT)fs.writeFileSync(process.env.AUWB_TEST_REPORT,JSON.stringify(results,null,2));if(results.some(r=>!r.passed))process.exitCode=1;
})();
